/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco.janelas;

import banco.codigos.Cadastro;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author salgadoPC
 */
public class CadastroTela extends javax.swing.JFrame {

    /**
     * Creates new form Cadastor
     */
    public CadastroTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeTX = new javax.swing.JTextField();
        CadastroLB = new javax.swing.JLabel();
        NomeLB = new javax.swing.JLabel();
        SenhaLB = new javax.swing.JLabel();
        SenhaTX = new javax.swing.JTextField();
        CadastroBT = new javax.swing.JButton();
        SaldoLB = new javax.swing.JLabel();
        SaldoTX = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NomeTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeTXActionPerformed(evt);
            }
        });

        CadastroLB.setText("Cadastrar Conta");

        NomeLB.setText("Nome");

        SenhaLB.setText("Senha");

        SenhaTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaTXActionPerformed(evt);
            }
        });

        CadastroBT.setText("Realizar Cadastro");
        CadastroBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroBTActionPerformed(evt);
            }
        });

        SaldoLB.setText("Saldo Inicial");

        SaldoTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaldoTXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(CadastroLB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(CadastroBT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SenhaLB)
                            .addComponent(SaldoLB)
                            .addComponent(NomeLB))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SenhaTX, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(NomeTX)
                            .addComponent(SaldoTX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CadastroLB)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeLB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SenhaTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SenhaLB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaldoLB)
                    .addComponent(SaldoTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(CadastroBT)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NomeTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeTXActionPerformed

    private void SenhaTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaTXActionPerformed

    private void CadastroBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroBTActionPerformed
        String nome = NomeTX.getText();
        String senha = String.valueOf(SenhaTX.getText());
        double saldo = Integer.parseInt(SaldoTX.getText());

        try {
            Cadastro cadastro = new Cadastro(nome, senha, saldo);
            cadastro.conta();
            dispose();
            JOptionPane.showMessageDialog(null, "Conta Criada! \n Sua Conta é: " + cadastro.getConta());

        } catch (IOException e) {
            e.printStackTrace();
        }
        Main run = new Main();
        run.setVisible(true);
    }//GEN-LAST:event_CadastroBTActionPerformed

    private void SaldoTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaldoTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaldoTXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroBT;
    private javax.swing.JLabel CadastroLB;
    private javax.swing.JLabel NomeLB;
    private javax.swing.JTextField NomeTX;
    private javax.swing.JLabel SaldoLB;
    private javax.swing.JTextField SaldoTX;
    private javax.swing.JLabel SenhaLB;
    private javax.swing.JTextField SenhaTX;
    // End of variables declaration//GEN-END:variables
}
