/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco.janelas;

import banco.codigos.Acessar;
import banco.codigos.Conta;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author salgadoPC
 */
public class Operacoes extends javax.swing.JFrame {

    /**
     * Creates new form Operacoes
     */
    public Operacoes(){
        try {
            initComponents();
            Conta menu = new Conta();
            menu.Leitura(Acessar.acesso, Acessar.Acconta);
            nomLB.setText("Ola, " + menu.getNome());
            ContaLB.setText("Conta: " + menu.getConta());
            salLB.setText("Saldo: R$ " + menu.getSaldo());
        } catch (IOException ex) {
            Logger.getLogger(Operacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SacarBT = new javax.swing.JButton();
        TransferirBT = new javax.swing.JButton();
        DepositarBT = new javax.swing.JButton();
        ExtratoBT = new javax.swing.JButton();
        SairBT = new javax.swing.JButton();
        TituloLB = new javax.swing.JLabel();
        nomLB = new javax.swing.JLabel();
        ContaLB = new javax.swing.JLabel();
        salLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SacarBT.setText("Sacar");
        SacarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SacarBTActionPerformed(evt);
            }
        });

        TransferirBT.setText("Transferencia");
        TransferirBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferirBTActionPerformed(evt);
            }
        });

        DepositarBT.setText("Depositar");
        DepositarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositarBTActionPerformed(evt);
            }
        });

        ExtratoBT.setText("Extrato");
        ExtratoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtratoBTActionPerformed(evt);
            }
        });

        SairBT.setText("Voltar");
        SairBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairBTActionPerformed(evt);
            }
        });

        TituloLB.setText("Caixa");

        nomLB.setText("Nome");

        ContaLB.setText("Conta");

        salLB.setText("Saldo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(TituloLB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SacarBT)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(DepositarBT)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ExtratoBT))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TransferirBT)
                                    .addGap(69, 69, 69)
                                    .addComponent(SairBT)))
                            .addComponent(nomLB, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(salLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContaLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloLB)
                .addGap(16, 16, 16)
                .addComponent(nomLB, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContaLB)
                .addGap(13, 13, 13)
                .addComponent(salLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepositarBT)
                    .addComponent(ExtratoBT))
                .addGap(18, 18, 18)
                .addComponent(SacarBT)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TransferirBT)
                    .addComponent(SairBT))
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SacarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SacarBTActionPerformed
        dispose();
        Sacar run = new Sacar();
        run.setVisible(true);
    }//GEN-LAST:event_SacarBTActionPerformed

    private void SairBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairBTActionPerformed
        JOptionPane.showMessageDialog(null, "Login Encerrado");
        dispose();
        Main run = new Main();
        run.setVisible(true);
        
    }//GEN-LAST:event_SairBTActionPerformed

    private void ExtratoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtratoBTActionPerformed
        dispose();
        Conta conta = new Conta();
        try {
            conta.Leitura(Acessar.acesso, Acessar.Acconta);
        } catch (IOException ex) {
            Logger.getLogger(Operacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        Extrato extrato = new Extrato(conta.getExtrato());
        extrato.setVisible(true);
    }//GEN-LAST:event_ExtratoBTActionPerformed

    private void DepositarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositarBTActionPerformed
        dispose();
        Depositar run = new Depositar();
        run.setVisible(true);
    }//GEN-LAST:event_DepositarBTActionPerformed

    private void TransferirBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferirBTActionPerformed
        dispose();
        Transferir run = new Transferir();
        run.setVisible(true);
    }//GEN-LAST:event_TransferirBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               // new Operacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContaLB;
    private javax.swing.JButton DepositarBT;
    private javax.swing.JButton ExtratoBT;
    private javax.swing.JButton SacarBT;
    private javax.swing.JButton SairBT;
    private javax.swing.JLabel TituloLB;
    private javax.swing.JButton TransferirBT;
    private javax.swing.JLabel nomLB;
    private javax.swing.JLabel salLB;
    // End of variables declaration//GEN-END:variables
}
